package br.iesb.meuprograma.apresentacao;

import br.iesb.meuprograma.entidades.ListAssunto;
import br.iesb.meuprograma.negocio.ListAssuntoBO;
import br.iesb.meuprograma.negocio.NegocioException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maicon
 */
public class JDialogListarAssunto extends javax.swing.JDialog {

    /**
     * Creates new form JDialogListarAssunto
     */
    public JDialogListarAssunto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonRemover = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jLabelListarAssunto = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAssunto = new javax.swing.JTable();
        jButtonAdi = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Assunto");
        setPreferredSize(new java.awt.Dimension(715, 500));

        jButtonRemover.setText("Remover");
        jButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar");

        jLabelListarAssunto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelListarAssunto.setText("Listar Assunto");

        jTableAssunto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), "Assunto 1", "Ativo"},
                { new Integer(2), "Assunto 2", "Ativo"},
                { new Integer(3), "Assunto 3", "Inativo"},
                { new Integer(4), "Assunto 4 ", "Inativo  "},
                { new Integer(5), "Assunto 5", "Ativo"}
            },
            new String [] {
                "ID", "Assunto", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableAssunto);
        if (jTableAssunto.getColumnModel().getColumnCount() > 0) {
            jTableAssunto.getColumnModel().getColumn(0).setMinWidth(100);
            jTableAssunto.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTableAssunto.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jButtonAdi.setText("Adicionar");
        jButtonAdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdiActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonAdi)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonRemover)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButtonListar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabelListarAssunto)
                            .addGap(542, 542, 542))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabelListarAssunto)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdi)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonRemover)
                    .addComponent(jButtonListar))
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = jTableAssunto.getSelectedRow();
        if (linhaSelecionada >= 0) {

        } else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
        }
        if (jTableAssunto.getSelectedRow() != -1) {
            int confirma = JOptionPane.showConfirmDialog(null, "A linha selecionada será excluido.", "Atenção", JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                DefaultTableModel remover = (DefaultTableModel) jTableAssunto.getModel();
                remover.removeRow(jTableAssunto.getSelectedRow());
            }
        }
    }//GEN-LAST:event_jButtonRemoverActionPerformed

    private void jButtonAdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdiActionPerformed
        ListAssunto assunto = new ListAssunto();
        ListAssuntoBO bo = new ListAssuntoBO();
        try {
            bo.inserir(assunto);
            JOptionPane.showMessageDialog(rootPane, "Dados adicionados com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);

        } catch (NegocioException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage(), "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAdiActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        int linhaSelecionada = -1;
        linhaSelecionada = jTableAssunto.getSelectedRow();
        if (linhaSelecionada >= 0) {

        } else {
            JOptionPane.showMessageDialog(null, "É necesário selecionar uma linha.");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogListarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogListarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogListarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogListarAssunto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogListarAssunto dialog = new JDialogListarAssunto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdi;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonRemover;
    private javax.swing.JLabel jLabelListarAssunto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAssunto;
    // End of variables declaration//GEN-END:variables
}
