/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.iesb.meuprograma.apresentacao;

import br.iesb.meuprograma.entidades.Anexo;
import br.iesb.meuprograma.entidades.Processo;
import br.iesb.meuprograma.negocio.NegocioException;
import br.iesb.meuprograma.negocio.ProcessoBO;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author daniboy
 */
public class JDialogCadastrarProcesso extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastrarProcesso
     */
    public JDialogCadastrarProcesso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNumProcesso = new javax.swing.JLabel();
        numProcesso = new javax.swing.JTextField();
        lblAssunto = new javax.swing.JLabel();
        lblDataProcesso = new javax.swing.JLabel();
        dataProcesso = new javax.swing.JTextField();
        comboAssunto = new javax.swing.JComboBox<>();
        lblDescricao = new javax.swing.JLabel();
        descricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        anexo = new javax.swing.JTextField();
        jButtonAdicionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAnexos = new javax.swing.JTable();
        jButtonSalvar = new javax.swing.JButton();
        jButtonDesistir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Cadastrar Processo");

        lblNumProcesso.setText("Nº do Processo:  ");

        numProcesso.setEditable(false);
        numProcesso.setText("99999999999");
        numProcesso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                numProcessoPropertyChange(evt);
            }
        });

        lblAssunto.setText("Assunto: ");

        lblDataProcesso.setText("Data do Processo: ");

        dataProcesso.setEditable(false);
        dataProcesso.setText("99/99/9999");
        dataProcesso.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dataProcessoPropertyChange(evt);
            }
        });

        comboAssunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Selecione o Assunto -- ", "Assunto 1", "Assunto 2", "Assunto 3" }));

        lblDescricao.setText("Descrição:");

        jLabel2.setText("Anexos: ");

        anexo.setText("Selecione um arquivo...");

        jButtonAdicionar.setText("Adicionar");
        jButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarActionPerformed(evt);
            }
        });

        anexoTable = new br.iesb.meuprograma.apresentacao.AnexoTableModel();
        jTableAnexos.setModel(anexoTable);
        jTableAnexos.setColumnSelectionAllowed(true);
        jTableAnexos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAnexosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableAnexos);

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonDesistir.setText("Desistir");
        jButtonDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonSalvar)
                            .addGap(63, 63, 63)
                            .addComponent(jButtonDesistir)
                            .addGap(213, 213, 213))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumProcesso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(lblDataProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dataProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAssunto)
                        .addGap(66, 66, 66)
                        .addComponent(comboAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDescricao)
                        .addGap(59, 59, 59)
                        .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(73, 73, 73)
                        .addComponent(anexo, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAdicionar)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataProcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumProcesso)
                            .addComponent(lblDataProcesso))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblAssunto))
                    .addComponent(comboAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblDescricao))
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addComponent(anexo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButtonAdicionar)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonDesistir))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarActionPerformed
        
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Anexar documentos");
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter  = new FileNameExtensionFilter("documentos", "pdf","doc","docx","odt","xls","xlsx","ods");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);
        if(result == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            if(selectedFile.length() < (10 * (1024*1024))){
               Anexo anexos = new Anexo();
               Random item = new Random();
               int num = 0;
               while (num <= 0){
                   num = item.nextInt(899999999);
               }
               anexos.setId(num);
               anexos.setNomeArquivo(selectedFile.getName());
               anexos.setLocal(selectedFile.getPath());
               anexoTable.addAnexo(anexos);   
            }else{
                JOptionPane.showMessageDialog(rootPane,"Arquivo selecionado é maior que 10 Mb. Selecione um arquivo de menor tamanho.", "Aviso",JOptionPane.WARNING_MESSAGE);
                selectedFile = null;
            }
        }
    }//GEN-LAST:event_jButtonAdicionarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        Processo processo = new Processo();
        processo.setNumProcesso(Integer.parseInt(numProcesso.getText()));
        processo.setDataProcesso((dataProcesso.getText()));
        processo.setAnexos(anexoTable.getTableData());
        processo.setDescricao(descricao.getText());
        String assunto = null;
        if(comboAssunto.getSelectedIndex() != 0){
            assunto =""+comboAssunto.getSelectedItem();
        } 
        processo.setAssunto(assunto);
        ProcessoBO bo = new ProcessoBO();
        try{
            bo.inserir(processo);
            JOptionPane.showMessageDialog(rootPane,"Inserido com sucesso!", "Informação",JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }catch(NegocioException e){
            JOptionPane.showMessageDialog(rootPane,e.getMessage(), "Informação",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void dataProcessoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dataProcessoPropertyChange
        // TODO add your handling code here:
        SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
        Date dataAtual = new Date(System.currentTimeMillis());
        dataProcesso.setText(sd.format(dataAtual));
    }//GEN-LAST:event_dataProcessoPropertyChange

    private void numProcessoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_numProcessoPropertyChange
        // TODO add your handling code here:
        Random radom = new Random();
        int num = 0;
        while (num <= 0){
            num = radom.nextInt(899999999);
        }
        numProcesso.setText(""+num);
    }//GEN-LAST:event_numProcessoPropertyChange

    private void jButtonDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesistirActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonDesistirActionPerformed

    private void jTableAnexosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAnexosMouseClicked
        // TODO add your handling code here:
        int col = jTableAnexos.getSelectedColumn();
        int linha = jTableAnexos.getSelectedRow();   
        if(jTableAnexos.getValueAt(linha, col) == "Remover"){
            int confirm = JOptionPane.showConfirmDialog (null, "Gostaria de remover o anexo?","Warning",JOptionPane.YES_NO_OPTION);
            if(confirm == JOptionPane.YES_OPTION){
                anexoTable.removeRow(linha);
            }
        }
    }//GEN-LAST:event_jTableAnexosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastrarProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadastrarProcesso dialog = new JDialogCadastrarProcesso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anexo;
    private javax.swing.JComboBox<String> comboAssunto;
    private javax.swing.JTextField dataProcesso;
    private javax.swing.JTextField descricao;
    private javax.swing.JButton jButtonAdicionar;
    private javax.swing.JButton jButtonDesistir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAnexos;
    private br.iesb.meuprograma.apresentacao.AnexoTableModel anexoTable;
    private javax.swing.JLabel lblAssunto;
    private javax.swing.JLabel lblDataProcesso;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblNumProcesso;
    private javax.swing.JTextField numProcesso;
    // End of variables declaration//GEN-END:variables
}
