package br.iesb.meuprograma.apresentacao;

import javax.swing.JInternalFrame;

public class JFramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFramePrincipal
     */
    
    static JInternalFrameCadastroUnidade objTelaCadastroUnidade;
    static JInternalFrameListarUnidade objTelaListarUnidade;
    
    public JFramePrincipal() {
        initComponents();
    }
    
    public static void addInternalFrame (JInternalFrame tela) {//Método para adicionar JInternalFrame na área de trabalho
        try {
            tela.setVisible(true);
            jDesktopPane.add(tela);//adiciona do DescktopPane
            //Centraliza a tela
            int larguraDk = jDesktopPane.getWidth();
            int alturaDK = jDesktopPane.getHeight();
            int larguraTela = tela.getWidth();
            int alturaTela = tela.getHeight();
            tela.setLocation(larguraDk / 2 - larguraTela / 2, alturaDK / 2 - alturaTela / 2);
            //seleciona a tela
            tela.setSelected(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void getInstanciaJanela(int tela) {//verifica a instância da tela, se for null cria um novo obj e add no descktopPane se não seleciona a tela.

        switch (tela) {
            case 1:
                if (objTelaCadastroUnidade == null){
                    objTelaCadastroUnidade = new JInternalFrameCadastroUnidade();
                    addInternalFrame(objTelaCadastroUnidade);
                }else{
                    try {
                        objTelaCadastroUnidade.setSelected(true);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            break;
            case 2:
                if(objTelaListarUnidade==null){
                    objTelaListarUnidade = new JInternalFrameListarUnidade();
                    addInternalFrame(objTelaListarUnidade);
                }else{
                    try {
                        objTelaListarUnidade.setSelected(true);
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    }
                }
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane = new javax.swing.JDesktopPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuSistema = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuAssuntos = new javax.swing.JMenu();
        jMenuItemCadastrarAssuntos = new javax.swing.JMenuItem();
        jMenuItemListarAssuntos = new javax.swing.JMenuItem();
        jMenuUnidades = new javax.swing.JMenu();
        jMenuItemCadastrarUnidade = new javax.swing.JMenuItem();
        jMenuItemListarUnidades = new javax.swing.JMenuItem();
        jMenuProcessos = new javax.swing.JMenu();
        jItemMenuCadatrarProcesso = new javax.swing.JMenuItem();
        jMenuItemPesquisarProcesso = new javax.swing.JMenuItem();
        jMenuItemTramitarProcesso = new javax.swing.JMenuItem();
        jMenuAjuda = new javax.swing.JMenu();
        jMenuItemSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Meu Programa");

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        jMenuSistema.setMnemonic('S');
        jMenuSistema.setText("Sistema");

        jMenuItemSair.setMnemonic('r');
        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSistema.add(jMenuItemSair);

        jMenuBarPrincipal.add(jMenuSistema);

        jMenuCadastro.setMnemonic('C');
        jMenuCadastro.setText("Cadastro");

        jMenuAssuntos.setText("Assuntos");

        jMenuItemCadastrarAssuntos.setText("Cadastrar Assuntos");
        jMenuItemCadastrarAssuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarAssuntosActionPerformed(evt);
            }
        });
        jMenuAssuntos.add(jMenuItemCadastrarAssuntos);

        jMenuItemListarAssuntos.setText("Listar Assuntos");
        jMenuItemListarAssuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarAssuntosActionPerformed(evt);
            }
        });
        jMenuAssuntos.add(jMenuItemListarAssuntos);

        jMenuCadastro.add(jMenuAssuntos);

        jMenuUnidades.setText("Unidades");

        jMenuItemCadastrarUnidade.setText("Cadastrar");
        jMenuItemCadastrarUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarUnidadeActionPerformed(evt);
            }
        });
        jMenuUnidades.add(jMenuItemCadastrarUnidade);

        jMenuItemListarUnidades.setText("Listar");
        jMenuItemListarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemListarUnidadesActionPerformed(evt);
            }
        });
        jMenuUnidades.add(jMenuItemListarUnidades);

        jMenuCadastro.add(jMenuUnidades);

        jMenuProcessos.setText("Processos");

        jItemMenuCadatrarProcesso.setText("Cadastrar Processo");
        jItemMenuCadatrarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemMenuCadatrarProcessoActionPerformed(evt);
            }
        });
        jMenuProcessos.add(jItemMenuCadatrarProcesso);

        jMenuItemPesquisarProcesso.setText("Pesquisar Processo");
        jMenuItemPesquisarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarProcessoActionPerformed(evt);
            }
        });
        jMenuProcessos.add(jMenuItemPesquisarProcesso);

        jMenuItemTramitarProcesso.setText("Tramitar Processo");
        jMenuItemTramitarProcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTramitarProcessoActionPerformed(evt);
            }
        });
        jMenuProcessos.add(jMenuItemTramitarProcesso);

        jMenuCadastro.add(jMenuProcessos);

        jMenuBarPrincipal.add(jMenuCadastro);

        jMenuAjuda.setMnemonic('j');
        jMenuAjuda.setText("Ajuda");

        jMenuItemSobre.setMnemonic('S');
        jMenuItemSobre.setText("Sobre");
        jMenuItemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSobreActionPerformed(evt);
            }
        });
        jMenuAjuda.add(jMenuItemSobre);

        jMenuBarPrincipal.add(jMenuAjuda);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSobreActionPerformed
        JDialogSobre dialog = new JDialogSobre(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemSobreActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemListarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarUnidadesActionPerformed
        getInstanciaJanela(2);
    }//GEN-LAST:event_jMenuItemListarUnidadesActionPerformed

    private void jMenuItemCadastrarUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarUnidadeActionPerformed
        getInstanciaJanela(1);
    }//GEN-LAST:event_jMenuItemCadastrarUnidadeActionPerformed

    private void jMenuItemCadastrarAssuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarAssuntosActionPerformed
        JDialogCadatroAssuntos dialogo = new JDialogCadatroAssuntos (this, true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastrarAssuntosActionPerformed

    private void jMenuItemListarAssuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemListarAssuntosActionPerformed
        JDialogListarAssunto dialogo = new JDialogListarAssunto(this,true);
        dialogo.setVisible(true);
    }//GEN-LAST:event_jMenuItemListarAssuntosActionPerformed
    
    private void jMenuItemPesquisarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarProcessoActionPerformed
        // TODO add your handling code here:
        JDialogPesquisarProcesso processoDialog = new JDialogPesquisarProcesso(new javax.swing.JFrame(),true);
        processoDialog.setVisible(true);
    }//GEN-LAST:event_jMenuItemPesquisarProcessoActionPerformed

    private void jItemMenuCadatrarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemMenuCadatrarProcessoActionPerformed
        // TODO add your handling code here:
        JDialogCadastrarProcesso cadastrarProcessoDialog = new JDialogCadastrarProcesso(new javax.swing.JFrame(), true);
        cadastrarProcessoDialog.setVisible(true);
    }//GEN-LAST:event_jItemMenuCadatrarProcessoActionPerformed
    
    private void jMenuItemTramitarProcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTramitarProcessoActionPerformed
        // TODO add your handling code here:
        JDialogTramitarProcesso tramitarProcesso = new JDialogTramitarProcesso(new javax.swing.JFrame(), true);
        tramitarProcesso.setVisible(true);
    }//GEN-LAST:event_jMenuItemTramitarProcessoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JMenuItem jItemMenuCadatrarProcesso;
    private javax.swing.JMenu jMenuAjuda;
    private javax.swing.JMenu jMenuAssuntos;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuItemCadastrarAssuntos;
    private javax.swing.JMenuItem jMenuItemCadastrarUnidade;
    private javax.swing.JMenuItem jMenuItemListarAssuntos;
    private javax.swing.JMenuItem jMenuItemListarUnidades;
    private javax.swing.JMenuItem jMenuItemPesquisarProcesso;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemSobre;
    private javax.swing.JMenuItem jMenuItemTramitarProcesso;
    private javax.swing.JMenu jMenuProcessos;
    private javax.swing.JMenu jMenuSistema;
    private javax.swing.JMenu jMenuUnidades;
    // End of variables declaration//GEN-END:variables
}
